-- Schema generated from live PostgreSQL database (jobmanager)
-- Date: 2025-09-09

-- =====================
-- customers
-- =====================
CREATE TABLE customers (
  customer_id text PRIMARY KEY,
  code text,
  name text,
  site_code text,
  phone text,
  mobile text,
  email text,
  website text,
  comment text,
  active boolean DEFAULT true,
  credit_terms text,
  mis_ref_1 text,
  mis_ref_2 text,
  account_manager_id text,
  company_number_type text,
  company_number text,
  account_status_id text,
  customer_tier_id text,
  date_created date DEFAULT CURRENT_DATE,
  last_modified_by text,
  tax_type_id text,
  discount_rate numeric(5,2),
  discount_based_on text,
  billing_customer_id text,
  customer_group_id text,
  freight_zone_id text,
  important_notes text,
  outstanding_balance numeric(15,2) DEFAULT 0,
  credit_limit numeric(15,2),
  currency_code text DEFAULT 'AUD',
  commission_rate numeric(5,2)
);

-- =====================
-- customer_contacts
-- =====================
CREATE TABLE customer_contacts (
  contact_id text PRIMARY KEY,
  customer_id text REFERENCES customers(customer_id),
  contact_type text,
  contact_title text,
  contact_first_name text,
  contact_surname text,
  contact_phone text,
  contact_mobile text,
  contact_email text,
  contact_website text,
  contact_comment text,
  email_invoice boolean DEFAULT false,
  is_primary boolean DEFAULT false
);

-- =====================
-- quotes
-- =====================
CREATE TABLE quotes (
  id text PRIMARY KEY,
  lineidentifier text,
  lineidentifiernoprefix text,
  quoteid text,
  quoteidnoprefix text,
  quotelineid text,
  quotedescription text,
  recipeid text,
  quotedate date,
  customerid text,
  customername text,
  quantity integer,
  sibling integer,
  siblingcount integer,
  revision integer,
  sizexmm double precision,
  sizeymm double precision,
  filename text,
  materialname text,
  laminatename text,
  finishingname text,
  printcolour text,
  tool text,
  cores text,
  handmachineapplied text,
  supply text,
  kinds integer,
  rolldirection text,
  linedescription text,
  deliverytoaddress text,
  profitcentrename text,
  status text,
  changehistory text,
  processed boolean DEFAULT false,
  notes text
);

-- =====================
-- jobs
-- =====================
CREATE TABLE jobs (
  job_id text PRIMARY KEY,
  customer_id text REFERENCES customers(customer_id),
  job_number text,
  material_id text,
  finishing_id text,
  qty_ordered integer,
  qty_per_roll integer,
  requires_joining boolean DEFAULT false,
  core_size text,
  web_width numeric(8,2),
  size_x numeric(8,2),
  size_y numeric(8,2),
  shape_id text,
  tool_id text,
  use_digital_cut boolean DEFAULT false,
  digital_cut_eligible boolean DEFAULT false,
  repeat_length numeric(8,2),
  max_step_qty integer,
  estimated_print_speed numeric(6,2),
  estimated_print_time integer,
  total_web_length numeric(10,2),
  material_overrun_allowance numeric(5,2) DEFAULT 5.0,
  job_status text DEFAULT 'pending',
  estimated_total_time integer,
  actual_total_time integer,
  profit_margin numeric(8,2),
  total_cost_aud numeric(12,2),
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  purchase_order_number text,
  order_date date DEFAULT CURRENT_DATE,
  due_date date,
  delivery_address text,
  rush_priority boolean DEFAULT false,
  special_instructions text,
  line_identifier text,
  line_identifier_no_prefix text,
  job_name text,
  recipe_id text,
  account_manager_name text,
  account_manager_email text,
  item_id text,
  product_id text,
  product_code text,
  product_name text,
  sibling integer,
  sibling_count integer,
  revision integer,
  approvers text,
  material_name text,
  finishing_name text,
  print_colour text,
  tool text,
  cores text,
  hand_machine_applied text,
  supply text,
  kinds integer,
  roll_direction text,
  line_description text,
  quote_id text,
  quote_line_id text,
  quote_date date,
  profit_centre_name text,
  processed boolean DEFAULT false,
  notes text,
  shipping_mode text,
  courier_company_name text,
  shipping_type_id text
);

-- =====================
-- job_operations
-- =====================
CREATE TABLE job_operations (
  job_operation_id text PRIMARY KEY,
  job_id text REFERENCES jobs(job_id),
  operation_id text,
  sequence_order double precision,
  depends_on_operation_id text,
  estimated_time_minutes integer,
  actual_time_minutes integer,
  setup_time_minutes integer,
  machine_id text,
  operator_id text,
  status text DEFAULT 'pending',
  priority_boost integer DEFAULT 0,
  start_time timestamp,
  end_time timestamp,
  notes text,
  barcode text,
  name text,
  sort double precision,
  completed_at timestamp
);
